import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useState } from "react";
import { NextPage } from "next";
import Translater from "@/components/Translater";

const inter = Inter({ subsets: ["latin"] });

const Home:NextPage = () => {
	const [lang, setLang] = useState<string>('');


	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<select onChange={(e) => setLang(e.target.value)} >
					<option value="ru">russian</option>
					<option value="french">french</option>
					<option value="tajik">tajik</option>
					<option value="german">german</option>
					<option value="japanese">japan</option>
					<option value="korean">korean</option>
				</select>
			
				<Translater lang={lang} />
			</main>
		</>
	);
}


export default Home